#!/bin/bash
CropID='jszwxe62b12e155e56190'
Secret='rGeHVQpTX0y5M-OO7zg3d9F1PyUeX9sPqcFI0C4-Y0vfE-9USFAoF-VpL76ProSz'
url="https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=${CropID}&corpsecret=${Secret}" 
Gtoken=$(/usr/bin/curl -s -G ${url} | awk -F'"' '{print $4}')
PURL="https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=$Gtoken"
DATE=`date "+%Y-%m-%d %H:%M:%S"`

AppID=1                       # 企业号中的应用id
UserID=$1                         # 部门成员id，zabbix中定义的微信接收者
PartyID=                         # 部门id，定义了范围，组内成员都可接收到消息
Msg=$(echo "$@" | cut -d" " -f3-) # 过滤出zabbix中传递的第三个参数
echo $UserID
echo $Msg
function body(){
        printf '{\n'
        printf '\t"touser":"'"$UserID"\"",\n"
        printf '\t"toparty":"'"$PartyID"\"",\n"
        printf '\t"msgtype":"text",\n'
        printf '\t"agentid":"'"$AppID"\"",\n"
        printf '\t"text":{\n'
        printf '\t\t"content":"'"$Msg"\""\n"
        #printf '\t"text": {\n'
        printf '\t},\n'
        printf '\t"safe":"0"\n'
        printf '}\n'
    }

    
echo ' '>> monitor.log
echo ${DATE}  >> monitor.log
body >> monitor.log
/usr/bin/curl  -s --data-ascii "$(body $1 $2 $3)" $PURL
